config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "ingredients#index"

  resources :ingredients

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  require 'pry' if Rails.env == 'develpment' || Rails.env == 'test'
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.order(:name).page params[:page]
  end

  def show
  end

  def new
    @ingredient = Ingredient.new(params[:ingredient])
  end

  def create
    begin
      Ingredient.create!(permitted_params)

      redirect_to ingredients_path
    rescue
      render action: :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def permitted_params
    params[:ingredient].permit(
      :name,
      :calories
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_ingredient.html.erb
<tr>
  <td>
    <%= link_to ingredient_path(ingredient.id), class: "btn btn-default" do %>
      <i class="fa fa-eye"></i>
    <% end %>

    <%= link_to edit_ingredient_path(ingredient.id), class: "btn btn-default" do %>
      <i class="fa fa-pencil"></i>
    <% end %>

    <%= link_to ingredient_path(ingredient.id), method: :delete, class: "btn btn-default" do %>
      <i class="fa fa-times"></i>
    <% end %>
  </td>

  <td><%= ingredient.name %></td>
  <td><%= ingredient.calories %></td>
</tr>

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/ingredients/create.html.erb</p>

app/views/ingredients/destroy.html.erb
<h1>Ingredients#destroy</h1>
<p>Find me in app/views/ingredients/destroy.html.erb</p>

app/views/ingredients/edit.html.erb
<h1>Ingredients#edit</h1>
<p>Find me in app/views/ingredients/edit.html.erb</p>

app/views/ingredients/index.html.erb
<h1><%= t('headers.ingredients') %></h1>

<div class="container-fluid">
  <%= link_to t('links.new_ingredient'), new_ingredient_path, class: 'btn btn-primary pull-right' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="col-md-2"><%= t('table_headers.actions') %></th>
      <th><%= t('table_headers.name') %></th>
      <th><%= t('table_headers.calories') %></th>
    </tr>
  </thead>

  <tbody>
    <%= render @ingredients %>
  </tbody>
</table>

<%= paginate @ingredients %>

app/views/ingredients/new.html.erb
<h1><%= t('headers.new_ingredient') %></h1>
<p>Find me in app/views/ingredients/new.html.erb</p>

<%= form_for @ingredient do |f| %>
  <div class="form-group">
    <%= f.label :name, t('labels.name') %>
    <%= f.text_field :name, class: 'form-control', placeholder: t('placeholders.ingredient_name') %>
  </div>

  <div class="form-group">
    <%= f.label :calories, t('labels.calories') %>
    <%= f.text_field :calories, class: 'form-control', placeholder: t('placeholders.ingredient_name') %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

app/views/ingredients/update.html.erb
<h1>Ingredients#update</h1>
<p>Find me in app/views/ingredients/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MealTime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>